List<Map<String, dynamic>> projects = [
  {
    'name': 'GoodCommerce App',
    'description': 'Mobile administrator application ',
    'technologies': [
      'Flutter',
      'Getx',
      'Firebase',
      'GraphQL',
      'In-App-Purchase',
    ],
    'images': '',
    'repositoryLink': '',
    'storesLinks': {'appstore': '', 'playstore': ''},
    'published': false,
  },
  {
    'name': 'GoodCommerce App',
    'description': 'Mobile administrator application ',
    'technologies': [
      'Flutter',
      'Getx',
      'Firebase',
      'GraphQL',
      'In-App-Purchase',
    ],
    'images': '',
    'repositoryLink': '',
    'storesLinks': {'appstore': '', 'playstore': ''},
    'published': false,
  },
  {
    'name': 'GoodCommerce App',
    'description': 'Mobile administrator application ',
    'technologies': [
      'Flutter',
      'Getx',
      'Firebase',
      'GraphQL',
      'In-App-Purchase',
    ],
    'images': '',
    'repositoryLink': '',
    'storesLinks': {'appstore': '', 'playstore': ''},
    'published': false,
  },
  {
    'name': 'GoodCommerce App',
    'description': 'Mobile administrator application ',
    'technologies': [
      'Flutter',
      'Getx',
      'Firebase',
      'GraphQL',
      'In-App-Purchase',
    ],
    'images': '',
    'repositoryLink': '',
    'storesLinks': {'appstore': '', 'playstore': ''},
    'published': false,
  },
];
