List<Map<String, dynamic>> projects = [
  {
    'name': 'GoodCommerce App',
    'description': 'Mobile administrator application ',
    'technologies': [
      'Flutter',
      'Getx',
      'Firebase',
      'GraphQL',
      'In-App-Purchase',
    ],
    'images': 'assets/images/goodcommerce-image.webp',
    'repository_link': 'aaaaaaaa',
    'stores_links': {'appstore': 'aa', 'playstore': 'aa'},
    'published': true,
  },
  {
    'name': 'GoodCommerce App',
    'description': 'Mobile administrator application ',
    'technologies': [
      'Flutter',
      'Getx',
      'Firebase',
      'GraphQL',
      'In-App-Purchase',
    ],
    'images': 'assets/images/goodcommerce-image.webp',
    'repository_link': '',
    'stores_links': {'appstore': '', 'playstore': ''},
    'published': false,
  },
  {
    'name': 'GoodCommerce App',
    'description': 'Mobile administrator application ',
    'technologies': [
      'Flutter',
      'Getx',
      'Firebase',
      'GraphQL',
      'In-App-Purchase',
    ],
    'images': 'assets/images/goodcommerce-image.webp',
    'repository_link': '',
    'stores_links': {'appstore': '', 'playstore': ''},
    'published': false,
  },
  {
    'name': 'GoodCommerce App',
    'description': 'Mobile administrator application ',
    'technologies': [
      'Flutter',
      'Getx',
      'Firebase',
      'GraphQL',
      'In-App-Purchase',
    ],
    'images': 'assets/images/goodcommerce-image.webp',
    'repository_link': '',
    'stores_links': {'appstore': '', 'playstore': ''},
    'published': false,
  },
];
